### ISSUE TITLE
user guide not searchable with mobile device

### ISSUE THREAD

**Issue by bionicles** [kstaats/karoo_gp#16]
the fact this user guide is exclusively hosted on github makes it impossible to open the file in the mobile browser and thus it is impossible to search without downloading it onto your device and opening it in an app. 

Would it be possible to host this pdf somewhere and add a link to the pdf in the readme?

**Comment by kstaats** [comment]
I was not aware of this. My apology.

Yes, will host it elsewhere. For now, I will send a copy to you 
directly, in the next email.

**Comment by kstaats** [comment]
Please fill out the form at https://overthesun.com/contact/ and I will 
then send the PDF to the email you provide there, for now.

**Comment by bionicles** [comment]
@kstaats Thank you Kai, I was able to download the PDF onto Evernote and search it that way. Would love to use this for Graph GP in TF 2.0 keras api

**Comment by kstaats** [comment]
Howard,

> @kstaats Thank you Kai, I was able to download the PDF onto Evernote and search it that way. Would love to use this for Graph GP in TF 2.0 keras api

Very good. Glad you got it to work.

Do not hesitate to ask for assistance in using / integrating Karoo GP.

Cheers,
kai

**Comment by kstaats** [comment]
I will be updating Karoo with the most recent libraries by the close of 2020. I encourage you to download this new release, when complete. Stay tuned!
