### ISSUE TITLE
How to introduce "if" condition to Karoo? (+Approach)

### ISSUE THREAD

**Issue by ducktalez** [kstaats/karoo_gp#18]
**How can the 'if-condition' be introduced to Karoo without problems with sympy, ast or tensorflow?**

I am currently developing a special gp-framework based on Karoo which shall include if-then-else. As it is already partially included, maybe you can help me out.

**Problem**

**Closure**
I assume a conversion between numbers and bool is prefered. (positive values (`>`) are `True`, `True` is integer 1), etc. . 
(Is this better than introducing 'bool'-operators?)

**Tensorflow**: 
If-then-else needs to become a tensor.

**Sympify** does not support `if (a) then (b) else (c)`. (and `ITE()` is bullshit) 
Solutions:
1. Get rid of sympify.
Yeah, obviously not.
2. Using Piecewise expression: `Piecewise((expr, cond),(expr, cond), ...)`, converted to if-then-else: ``Piecewise((b, a),(c, True))``
-> Is imho too far away from the original if-then-else statement
-> Tensorflow seemingly offers no 'Piecewise'-similar tensor
3. Passing through custom expressions like `ifte(a, b, c)`. These get sympify'ed as far as possible.
-> Ast+Tensorflow run into problems with partially sympify'ed expressions like 
`ifte(True, 1, 2)` (`True` is a nameConstant) or 
`ifte(variable_1*2, b, c)` (Tensor not of type boolean). 
The expression can not be further reduced by sympify.
4. Write own sympify class (see below). Unfortunately this does not work, sympify is called on a string where the class is not known.
```
from sympy import Function

class ifte(Function):
    nargs = 3

    @classmethod
    def eval(cls, a, b, c):
        return b if a else c
```

**My current solution**

- If is modeled as `ifte(a, b, c)` (sympify function passthrough).
- ast-node functions are checked for `ifte`, the conditional-tensor is forced to be boolean
- Karoo operators: `'ifte': tf.compat.v2.where, `

This does not make me completely happy though. 
(Also: Sympify's `/ 0`-caused `zoo` is happening. Is string-replaced with '1000000'.)

**What is the best solution?**

What do you think would be the best approach to include if-then-else?
Are my assumptions correct?
Also, I am not sure how to handle closure (e. g. replacing sin(x) with ifte(x)).

**Comment by ducktalez** [comment]
Just realised that option 4. 'Write own sympify class' is probably very possible. Closing, at least for now.

**Comment by kstaats** [comment]
My apology for the delayed response.

In the case of this unique use of Karoo (which I am excited to see 
unfold), I believe you are taking the correct approach. But to be clear, 
the TF support of operators is custom built, so it may be possible with 
the invocation of TF to expand the support a bit. I am checking with 
Iurii who implemented TF in Karoo.

In the mean time, keep me informed as to your progress.

kai
