### ISSUE TITLE
Need to provide ERCs

### ISSUE THREAD

**Issue by Vaguery** [kstaats/karoo_gp#3]
Success in most symbolic regression and classification problems depends on the use of Ephemeral Random Constants as part of the solution library. As far as I understand it, in this version one has to explicitly provide specific constants, as part of the training data set.

As things stand, even with the availability of user-provided specific constants, any search that requires numerical optimization of coefficients is spending most of its effort on _constructing_ numerical arguments, rather than actually fitting qualitative curves or decision planes.
### A simple example:

One of the pedagogic examples I always use is the _birthday polynomial_. Given your own birthday in `year month-number day-number` format, and then attempt symbolic regression on a dataset of

``` text
y = year + month-number * x + day-number * x * x
```

Without ERCs, symbolic regression on this simple polynomial spends most of its effort trying to construct large numbers from units. The interplay between this "sub-task" of actually constructing large constants from small ones, and the more important task of _explaining the data_ (which is usually the intent of the user) can lead to trouble, since from the standpoint of the GP system itself there is no differentiation between these tasks.

**Comment by kstaats** [comment]
Thank you Bill for your input and support.

Karoo GP does in fact randomly select constants (coefficients), from a 
user defined list. These can be fractional (.1, .2, .3, ... .n) or 
integer (1, 2, 3 ... n). But I am working on a design which will make it 
simpler to introduce constants, instead of adding them to the columns of 
the data .csv.

kai
