### ISSUE TITLE
Problem with new karoo

### ISSUE THREAD

**Issue by abdualhag** [kstaats/karoo_gp#5]
Hey;
Kstaats; After installing tensorflow and running the new karoo and finding out that the new karoo does not support exp and the other functions and deciding to go back to old karoo as I need them more than the speed  only to find out that I cannot run old karoo no longer and simply getting the following the error:
` We have constructed a population of 100 Trees for Generation 1

 Evaluate the first generation of Trees ...
Traceback (most recent call last):
  File "karoo_gp_main.py", line 208, in <module>
    gp.fx_fitness_gym(gp.population_a) # 1) extract polynomial from each Tree; 2) evaluate fitness, store; 3) display
  File "/home/abdu/Downloads/karoo/karoo_gp_base_class.py", line 1414, in fx_fitness_gym
    self.fx_eval_poly(population[tree_id]) # extract the expression
  File "/home/abdu/Downloads/karoo/karoo_gp_base_class.py", line 1185, in fx_eval_poly
    self.algo_raw = self.fx_eval_label(tree, 1) # pass the root 'node_id', then flatten the Tree to a string
  File "/home/abdu/Downloads/karoo/karoo_gp_base_class.py", line 1246, in fx_eval_label
    return self.fx_eval_label(tree, tree[9, node_id]) + tree[6, node_id] + self.fx_eval_label(tree, tree[10, node_id])
  File "/home/abdu/Downloads/karoo/karoo_gp_base_class.py", line 1236, in fx_eval_label
    if tree[6, node_id] == 'not': tree[6, node_id] = ', not' # temp until this can be fixed at data_load
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
`
The problem did not appear before installing tensorflow. Even worse; after uninstalling tensorflow, I still get the same error. I hope you have some recommendation of how I might fix the problem.
Best;

**Comment by kstaats** [comment]
Thank you for reaching out to me.

Yes, it is correct that the new release does not support cos, sin, log, 
nor exp. We are working to re-integrate these soon. I need to make that 
more clear in the documentation, as I do not desire to cause frustration.

Fortunately, I know exactly what happened with the error you have 
described (for it happened to me too!). With the update from Ubuntu 
14.04 to 16.04, the Python related libraries also incremented.

1) In karoo_gp_base_class.py, search for "def fx_eval_label".

2) In this method, insert a new line:

	node_id = int(node_id)

... just before the start of the recursive function. This forces the 
variable node_id to an integer state. I don't know why this worked 
before, but it makes sense.

3) Do the same thing for the next method down, "def fx_eval_id"

That's all it takes! :)

kai

**Comment by abdualhag** [comment]
Thanks;
It worked like magic, I really appreciated.
I hope the new version will support cos, exp, log soon, the speed difference is huge.

**Comment by kstaats** [comment]
Yes, it will. Just been swamped with the completion and subsequent
launch of my film "LIGO Detection" (www.newscientist.com/ligodetection)
this past two months. Now diving back into coding. Another version
should be sync'd tonight or tomorrow with improved run-time logging.

Then Iurii and I will work on regaining support for trig functions.

I would love to hear how you are using Karoo. Contact me off-thread some
time!
