### ISSUE TITLE
'Full' trees are not actually full

### ISSUE THREAD

**Issue by granawkins** [kstaats/karoo_gp#52]
(This issue affects the current branch but is not recent. It also affects 4154711866485b876a1f1f4112d9044b76863145, which is from March 20)

Karoo supports 3 tree generation methods:
- Full: Trees are symmetrical out to the maximum depth. For default max depth (3) this makes a total of 15 nodes.
- Grow: Trees add nodes one-by-one, flipping a coin at each one to see whether to terminate or continue (grow) up to the maximum depth. So the number of nodes is always between 3 and 15.
- Ramped 50/50: Model is initialized with 50% full trees and 50% grow trees.

In the full method, all of the trees are 15 nodes long as expected. However, in the ramped method (the default) with a population 100 (the default), <20 are 15 nodes (out of expected 50), and the rest shorter - I believe this is a bug. 

To see for yourself: Run the default simulation, look at the logs in runs/[date]/population_a.csv, look at the size of the first generation. This issue affects the current branch, but it also affects 4154711866485b876a1f1f4112d9044b76863145 which is from March 20 (as far back as I checked)

My latest update has a different api for generating trees, so the logic on making populations is new, so 50/100 are actually 15 nodes long. For this reason, the outputs are different, and the test doesn't pass.

**Comment by granawkins** [comment]
I misunderstood, it's right. From the user manual, "Ramped Half/Half initialises the first population with a 50/50 split of Full/Grow methods, **and a spread of depths from min to max**."

[Here's](https://github.com/kstaats/karoo_gp/blob/b6d72f3f0f795885ecf3e456e27016d63fc0a802/karoo_gp/base_class.py#L834) the code that does it. A simplified version for (population=100, depth=3):
```
n_cycles = int(population/2/depth)
for i in range(n_cycles):
   for d in range(depth):
      tree.generate(type='full', depth=d)
      tree.generate(type='grow', depth=d)
```

False alarm! Will update my code accordingly.

**Comment by kstaats** [comment]
Correct.
