### ISSUE TITLE
 tf.map_fn in population.py problem

### ISSUE THREAD

**Issue by asksak** [kstaats/karoo_gp#72]
Problem with dtype in tf.map_fn (file population.py), dtype replaced with  fn_output_signature

working format:

pred_labels = tf.map_fn(fx_fitness_labels_map,
                                            result, fn_output_signature=(tf.int32, tf.string),
                                            swap_memory=True)

**Comment by granawkins** [comment]
This bit of code was removed in the `engine-api` update so I'll close it. If there's a similar issue, add to #73 for now.

**Comment by kstaats** [comment]
Thank you Aymen. Received and processing.
