### ISSUE TITLE
Tree Error!

### ISSUE THREAD

**Issue by asksak** [kstaats/karoo_gp#75]
Hello all,

please review the tree below, which is a result of running the current version, and also occurred before the last commits:

What is this section of the tree?

sl
pw
sl

In fact I'm finding it hard to read this LISP tree, the whole tree does not make sense?

**_I hope I am wrong_**, but if not, this is the main part that needs current attention.

<img width="437" alt="Tree" src="https://user-images.githubusercontent.com/17875288/176113096-c5d0364d-f9a9-4baf-a530-11d71775d4cc.png">

**Comment by granawkins** [comment]
These are separate trees, with just a single space between each (will make the separation clearer). The three in the middle (sl, pw, sl) are 3 different trees, and their sympified expression is just that. e.g. `((sl) + ((sl) - (sl))) = (sl)`
