### ISSUE TITLE
Install process - Other

### ISSUE THREAD

**Issue by arita37** [kstaats/karoo_gp#8]
Thanks for your hard work.

1) AS TF, Scikit, packages are evolving a lot, it would be useful to document:
 For each release of KAROO_GP:
      Dependency list  (TF 1.0.1,   .....) of Python packages.
      Regression test in a folder test_regression: 
             input_data
             test_01.py

We can check install easily as well as the results.

2) We may want to integrate into other python data processing/code.
is there a way to import karoo as a package ?
       import karoo as ka

3) For some problems, we may want to limit the operation list 
(ex:  cyclical data, we want to remove sin and keep only keep cos(a*t+b) )
Is there a way to add a config file than karoo can read (so we don't have to change the core source).

4) What about custom primitive ?
  It may help for complex modelling and reducing tree depth.
  Operator Primitive:   exp( -a *x**2)

Ex: Multi-period data (5  <> period) and we split into medium period to simplify the problem.

**Comment by drdangersimon** [comment]
I think we could solve number 1 by packaging Karoo. In the setup.py we can include the current versions of the different packages. Creating a examples path would also make this code more accessible and solve the not changing source code issue too.

**Comment by arita37** [comment]
Hello,

Am working myself on auto test-regression as well as auto-documentation of python packages,
when ready would be glad to send to you.
(It sounds minor and very helpful when doing production-type release of code, spend time on doc and full testing...).

For packaging there pip and conda, but conda is better if you have binaries or boost library : 
Reference:
https://goo.gl/fDCAam
https://goo.gl/asFTfh

**Comment by kstaats** [comment]
Thank you all for your interest and support. I will respond in full, 
next week, as I am fully consumed on another project at this time.

**Comment by kstaats** [comment]
Arita,

> Thanks for your hard work.

Thank you for your support! And thank you for your patience.


> 1) AS TF, Scikit, packages are evolving a lot, it would be useful to document:
>  For each release of KAROO_GP:
>       Dependency list  (TF 1.0.1,   .....) of Python packages.
>       Regression test in a folder test_regression:
>              input_data
>              test_01.py
>
> We can check install easily as well as the results.

Per Thuso's email, yes, proper packaging will resolve this. To this end, 
I am working to first break the massive base_class into sep files, 
similar to the internal ### labels ### as currently provided.

I need to learn how to do the above lists. And per your second post, 
once you have learned how to conduct the auto-regression testing, let me 
know :)


> 2) We may want to integrate into other python data processing/code.
> is there a way to import karoo as a package ?
>        import karoo as ka

Yes, that will be cool. Will look at this once the proper packaging is done.


> 3) For some problems, we may want to limit the operation list
> (ex: cyclical data, we want to remove sin and keep only keep cos(a*t+b) )
> Is there a way to add a config file that karoo can read (so we don't have to change the core source).

If I understand your concern, then you are speaking of the operators, 
that is easily done by simply removing 'sin' (in your example) from the 
operators_[KERNEL].csv file.


> 4) What about custom primitive ?
>   It may help for complex modeling and reducing tree depth.
>   Operator Primitive: exp(-a * x**2)

The way I have done this, to date, is by calling this a 'custom 
feature'. For example, in my .csv file, I will create a new column (new 
feature) and execute 'exp(-a * x**2)' this *before* running Karoo. The 
output of this expression is a single number which holds the value of 
the full expression. So, it becomes a new column with a new heading 
name, such as "cfa" for "custom feature a".

Or you can insert this into the operators_[KERNEL].csv file in its own 
line.

kai

**Comment by kstaats** [comment]
Arita,

> 1) AS TF, Scikit, packages are evolving a lot, it would be useful to document:
>  For each release of KAROO_GP:
>       Dependency list  (TF 1.0.1,   .....) of Python packages.
>       Regression test in a folder test_regression:
>              input_data
>              test_01.py
>
> We can check install easily as well as the results.
 >
> 2) We may want to integrate into other python data processing/code.
> is there a way to import karoo as a package ?
>        import karoo as ka

I am eager to return to this discussion, if you remain engaged.

Cheers,
kai

**Comment by arita37** [comment]
1st step:

Is there any way easy way to refactor
cli input to one big function input ?

One trivial way is to execute as subprocess:

from executor import execute
cmd = “”
execute( cmd  )








On Feb 28, 2018, at 9:08, Kai Staats <notifications@github.com> wrote:

Arita,

> 1) AS TF, Scikit, packages are evolving a lot, it would be useful to document:
> For each release of KAROO_GP:
> Dependency list (TF 1.0.1, .....) of Python packages.
> Regression test in a folder test_regression:
> input_data
> test_01.py
>
> We can check install easily as well as the results.
>
> 2) We may want to integrate into other python data processing/code.
> is there a way to import karoo as a package ?
> import karoo as ka

I am eager to return to this discussion, if you remain engaged.

Cheers,
kai
―

**Comment by kstaats** [comment]
Have you used the Server version of Karoo? It is fully sys arg scripted 
such that an entire run is configured in one command.
