### ISSUE TITLE
Logic & Comparison

### ISSUE THREAD

**Issue by asksak** [kstaats/karoo_gp#90]
I understand how logic operators and comparison operators are used in the latest Karoo update, however, I was wondering if the a functionality to implement the statement below could be incorporated:

(a if (c>d) or (c>e) else f)

Currently, this is not possible, but this functionality is very important. Boolean algebra order of operations is NOT then AND then OR.

**Comment by granawkins** [comment]
Yes, that should be supported. It'd be `((a)if((c)>(d))else(f))`.

**Comment by asksak** [comment]
Let me test it again, I am sure I bumped into something. Let me get back to you. 

Thanks for the brilliant code by the way

**Comment by asksak** [comment]
> Yes, that should be supported. It'd be `((a)if(((c)>(d))or((c)>(e)))else(f))`.
> 
> 
> 
> I see what you mean about parsing order. I think it won't be an issue, because of parenthesis. 

Pardon me, yes it works
